version: "3"
services:
  php: 
    build: 
      context: ${FOLDER_CONFIG_DOCKER}
      dockerfile: php
      args:
        PHP_VERSION: ${PHP_VERSION}
    links: 
      -  mysql
#    ports:
#      -  ${PHPFPM_PORT}:9000
    container_name: "php"
    volumes: 
      -  ./data/www/:/var/www/html/
      -  ./config/php.ini:/usr/local/etc/php/php.ini
    restart: always
    networks:
      -  internal 
  nginx:
    build: 
      context: ${FOLDER_CONFIG_DOCKER}
      dockerfile: nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    container_name: "nginx"
    ports:
      -  ${NGINX_PORT_SERVER}:80
    links: 
      -  mysql
      -  php
    volumes: 
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/www/:/var/www/html/
    restart: always
    networks:
      -  internal
  mysql:
    build: 
      context: ${FOLDER_CONFIG_DOCKER}
      dockerfile: mysql
      args: 
        MYSQL_VERSION: ${MYSQL_VERSION}
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      -  ${MYSQL_PORT}:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./data/MySQL:/var/lib/mysql
    restart: always
    networks:
      -  internal
  pma:
    build: 
      context: ${FOLDER_CONFIG_DOCKER}
      dockerfile: pma
      args:
        PMA_VERSION: ${PMA_VERSION}
    container_name: "pma"
    links:
      - mysql:mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      DATABASE: test
    restart: always
    networks:
      -  internal
#  jenkins:
#    build:
#      context: ${FOLDER_CONFIG_DOCKER}
#      dockerfile: jenkins
#      args:
#        JENKINS_VERSION: ${JENKINS_VERSION}
#    container_name: "jenkins"
#    ports:
#      - ${JENKINS_PORT}:8080
#      - ${JENKINS_AGENT_PORT}:50000
#    volumes:
#      - ./data/jenkins/:/var/jenkins_home/
#    restart: always 
#  jira:
#    build:
#      context: ${FOLDER_CONFIG_DOCKER}
#      dockerfile: jira
#      args:
#        JIRA_VERSION: ${JIRA_VERSION}
#    container_name: "jira"
#    ports:
#      -  ${JIRA_PORT}:8080
#    restart: always
#    networks:
#      -  internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.1/28
