version: "3"
services:
  php: 
    build: 
      context: ./docker_config
      dockerfile: php
    links: 
      -  mysql
    ports:
      -  9000:9000
    container_name: "php"
    volumes: 
      -  ./data/www/:/var/www/html/
  nginx:
    build: 
      context: ./docker_config
      dockerfile: nginx
    container_name: "nginx"
    ports:
      -  80:80
    links: 
      -  mysql
      -  php
    volumes: 
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/www/:/var/www/html/
  mysql:
    build: 
      context: ./docker_config
      dockerfile: mysql
    container_name: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      -  3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    volumes:
      - ./data/MySQL:/var/lib/mysql
  pma:
    build: 
      context: ./docker_config
      dockerfile: pma
    container_name: "pma"
    links:
      - mysql:mysql
    ports:
      - 8000:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      DATABASE: test
  jenkins:
    build:
      context: ./docker_config
      dockerfile: jenkins
    container_name: "jenkins"
    ports:
      - 8001:8080
      - 50000:50000
    volumes:
      - ./data/jenkins/:/var/jenkins_home/
  jira:
    build:
      context: ./docker_config
      dockerfile: jira
    container_name: "jira"
    ports:
      -  8002:8080

